//! Renders `latex/generated/resume-data.tex`: data macros only.
//!
//! Layout stays in `latex/main.tex`, which defines the presentation hooks the
//! data macros call (`\ResumeEntry`, `\ResumeEntrySep`, `\ResumeHighlights`,
//! `\ResumeTag`, `\ResumeInfo`), so this module is independent of the LaTeX
//! template. Line breaks and `%` placement mirror a hand-written resume, since
//! TeX turns newlines into (sometimes visible) spaces.

use std::fmt::Write;

use anyhow::bail;
use resume_model::{Education, Project, Resume, RichText, SkillGroup, Work};

/// Macros whose argument is a skill-group id; `main.tex` references groups
/// through these (checked by `cargo gen check`).
pub const SKILL_MACROS: &[&str] = &[
    "ResumeSkillGroup",
    "ResumeSkillName",
    "ResumeSkillTags",
    "ResumeSkillItems",
];

/// Info-field macros AltaCV defines via `\NewInfoField` in altacv.cls. A
/// `basics.profiles[].network` must lowercase to one of these, since it
/// becomes a LaTeX control-sequence name (`\csname <network>\endcsname`);
/// anything else compiles here but fails pdflatex with an undefined-command
/// error deep in the generated file.
const ALTACV_NETWORKS: &[&str] = &[
    "email",
    "mailaddress",
    "phone",
    "homepage",
    "twitter",
    "xtwitter",
    "linkedin",
    "github",
    "orcid",
    "location",
];

const HEADER: &str = "\
% GENERATED by resume-gen from content/resume.yaml -- do not edit.
% Regenerate with `cargo gen latex`. Layout and styling live in main.tex, which
% defines the presentation hooks used below:
%   \\ResumeEntry{title}{organization}{dates}{location}{body}, \\ResumeEntrySep,
%   \\ResumeHighlights{items}, \\ResumeTag{text}, \\ResumeInfo{field}{value}
";

pub fn render(resume: &Resume) -> anyhow::Result<String> {
    let basics = &resume.basics;
    for profile in &basics.profiles {
        let network = profile.network.to_lowercase();
        if !ALTACV_NETWORKS.contains(&network.as_str()) {
            bail!(
                "basics.profiles: network `{}` isn't one of AltaCV's info fields ({}) -- \
                 pdflatex would fail on an undefined \\{network} command",
                profile.network,
                ALTACV_NETWORKS.join(", "),
            );
        }
    }

    let mut out = String::from(HEADER);

    let _ = writeln!(out);
    define(&mut out, "ResumeName", &escape(&basics.name));
    define(&mut out, "ResumeTagline", &escape(&basics.label));

    // Contact details go through AltaCV's detokenizing info fields, so they
    // are emitted verbatim (the loader rejects LaTeX special characters).
    let mut info = vec![
        ("email".to_owned(), basics.email.clone()),
        ("location".to_owned(), basics.location.to_string()),
    ];
    info.extend(
        basics
            .profiles
            .iter()
            .map(|profile| (profile.network.to_lowercase(), profile.username.clone())),
    );
    let info: Vec<String> = info
        .iter()
        .map(|(field, value)| format!("  \\ResumeInfo{{{field}}}{{{value}}}"))
        .collect();
    // The trailing newline keeps the space after the last field, as hand-written.
    define_block(
        &mut out,
        "ResumePersonalInfo",
        &format!("{}\n", info.join("\n")),
    );

    define(&mut out, "ResumeSummary", &rich(&basics.summary));

    let _ = writeln!(out, "\n% Sections: entries separated by \\ResumeEntrySep.");
    define_block(
        &mut out,
        "ResumeExperience",
        &entries(resume.work.iter().map(work)),
    );
    define_block(
        &mut out,
        "ResumeProjects",
        &entries(resume.projects.iter().map(project)),
    );
    define_block(
        &mut out,
        "ResumeEducation",
        &entries(resume.education.iter().map(education)),
    );
    let languages: Vec<String> = resume
        .languages
        .iter()
        .map(|l| escape(&l.to_string()))
        .collect();
    define_block(&mut out, "ResumeLanguages", &tags(&languages));

    let _ = writeln!(
        out,
        "\n% Skill groups by x-id: \\ResumeSkillName{{id}}, \\ResumeSkillTags{{id}}, \\ResumeSkillItems{{id}}."
    );
    out.push_str("\\newcommand{\\ResumeSkillName}[1]{\\csname resume@skill@name@#1\\endcsname}\n");
    out.push_str("\\newcommand{\\ResumeSkillTags}[1]{\\csname resume@skill@tags@#1\\endcsname}\n");
    out.push_str(
        "\\newcommand{\\ResumeSkillItems}[1]{\\csname resume@skill@items@#1\\endcsname}\n",
    );
    for group in &resume.skills {
        skill_group(&mut out, group);
    }
    Ok(out)
}

fn define(out: &mut String, name: &str, body: &str) {
    let _ = writeln!(out, "\\newcommand{{\\{name}}}{{{body}}}");
}

/// Multi-line macro body; `%` keeps line ends from adding spaces at the edges.
fn define_block(out: &mut String, name: &str, body: &str) {
    let _ = writeln!(out, "\\newcommand{{\\{name}}}{{%\n{body}%\n}}");
}

fn skill_group(out: &mut String, group: &SkillGroup) {
    let keywords: Vec<String> = group.keywords.iter().map(|k| escape(k)).collect();
    let items: Vec<String> = keywords.iter().map(|k| format!("\\item {k}")).collect();
    let id = &group.id;
    let _ = writeln!(
        out,
        "\\csdef{{resume@skill@name@{id}}}{{{}}}",
        escape(&group.name)
    );
    let _ = writeln!(
        out,
        "\\csdef{{resume@skill@tags@{id}}}{{%\n{}%\n}}",
        tags(&keywords)
    );
    let _ = writeln!(
        out,
        "\\csdef{{resume@skill@items@{id}}}{{%\n{}%\n}}",
        items.join("\n")
    );
}

/// One tag per line: the line breaks are the spaces between tags.
fn tags(escaped: &[String]) -> String {
    escaped
        .iter()
        .map(|tag| format!("\\ResumeTag{{{tag}}}"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Entries separated by blank lines (paragraph breaks) around the separator.
fn entries(entries: impl Iterator<Item = String>) -> String {
    entries.collect::<Vec<_>>().join("\n\n\\ResumeEntrySep\n\n")
}

fn entry(
    title: &str,
    organization: &str,
    dates: &str,
    location: Option<&str>,
    body: &str,
) -> String {
    format!(
        "\\ResumeEntry{{{}}}{{{}}}{{{}}}{{{}}}{{{body}}}",
        escape(title),
        escape(organization),
        escape(dates),
        location.map(escape).unwrap_or_default(),
    )
}

fn work(work: &Work) -> String {
    let body = if work.highlights.is_empty() {
        String::new()
    } else {
        let items: Vec<String> = work
            .highlights
            .iter()
            .map(|h| format!("\\item {}", rich(h)))
            .collect();
        format!("%\n\\ResumeHighlights{{%\n{}%\n}}", items.join("\n"))
    };
    entry(
        &work.position,
        &work.organization,
        &work.dates.to_string(),
        work.location.as_deref(),
        &body,
    )
}

/// Body: “Title” – description.
fn project(project: &Project) -> String {
    let mut body = escape(&format!("“{}”", project.title));
    if let Some(description) = &project.description {
        body.push_str(&escape(" – "));
        body.push_str(&rich(description));
    }
    entry(
        &project.heading(),
        "",
        &project.dates.to_string(),
        project.location.as_deref(),
        &body,
    )
}

fn education(education: &Education) -> String {
    let body = education
        .courses_sentence()
        .map(|s| escape(&s))
        .unwrap_or_default();
    entry(
        &education.title(),
        &education.institution,
        &education.dates.to_string(),
        education.location.as_deref(),
        &body,
    )
}

pub fn rich(text: &RichText) -> String {
    crate::spans::render(
        text,
        escape,
        |escaped, _raw| format!("\\texttt{{{escaped}}}"),
        |s| format!("\\emph{{{s}}}"),
        |s| format!("\\textbf{{{s}}}"),
        |s, url| format!("\\href{{{}}}{{{s}}}", escape_url(url)),
    )
}

/// Plain Unicode text to LaTeX (pdflatex with utf8 inputenc + T1 fontenc).
pub fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '&' | '%' | '$' | '#' | '_' | '{' | '}' => {
                out.push('\\');
                out.push(c);
            }
            '~' => out.push_str("\\textasciitilde{}"),
            '^' => out.push_str("\\textasciicircum{}"),
            '\\' => out.push_str("\\textbackslash{}"),
            '–' => out.push_str("--"),
            '—' => out.push_str("---"),
            '·' => out.push_str("\\textperiodcentered{}"),
            '“' => out.push_str("``"),
            '”' => out.push_str("''"),
            '‘' => out.push('`'),
            '’' => out.push('\''),
            '…' => out.push_str("\\dots{}"),
            '\u{a0}' => out.push('~'),
            _ => out.push(c),
        }
    }
    out
}

/// URLs inside a macro definition: `#` and `%` must be escaped for \href.
fn escape_url(url: &str) -> String {
    url.replace('\\', "/")
        .replace('%', "\\%")
        .replace('#', "\\#")
}

#[cfg(test)]
mod tests {
    use resume_model::{Span, Style};

    use super::*;

    #[test]
    fn escapes_special_characters() {
        assert_eq!(
            escape("Pair & Mob, 71%, C#, a_b {x} ~ ^ \\"),
            "Pair \\& Mob, 71\\%, C\\#, a\\_b \\{x\\} \\textasciitilde{} \\textasciicircum{} \\textbackslash{}"
        );
    }

    #[test]
    fn maps_typography() {
        assert_eq!(
            escape("A · B – C — D “q” it’s…"),
            "A \\textperiodcentered{} B -- C --- D ``q'' it's\\dots{}"
        );
        assert_eq!(escape("DirectX\u{a0}9"), "DirectX~9");
    }

    #[test]
    fn renders_rich_text() {
        let text = RichText(vec![
            Span::plain("see "),
            Span {
                text: "docs".into(),
                style: Style {
                    bold: true,
                    ..Style::default()
                },
                link: Some("https://x.org/a#b".into()),
            },
        ]);
        assert_eq!(
            rich(&text),
            "see \\href{https://x.org/a\\#b}{\\textbf{docs}}"
        );
    }

    #[test]
    fn rejects_a_profile_network_altacv_does_not_define() {
        let yaml = "\
basics:
  name: A
  label: B
  email: a@b.com
  location: { city: X }
  summary: S
  profiles:
    - { network: Mastodon, username: u, url: https://example.com }
";
        let resume = resume_model::load_str(yaml).unwrap_or_else(|e| panic!("{e}"));
        let error = render(&resume).unwrap_err();
        assert!(error.to_string().contains("Mastodon"), "{error}");
    }

    #[test]
    fn accepts_altacv_profile_networks_case_insensitively() {
        let yaml = "\
basics:
  name: A
  label: B
  email: a@b.com
  location: { city: X }
  summary: S
  profiles:
    - { network: GitHub, username: u, url: https://github.com/u }
";
        let resume = resume_model::load_str(yaml).unwrap_or_else(|e| panic!("{e}"));
        assert!(render(&resume).unwrap().contains("\\ResumeInfo{github}{u}"));
    }
}

#[cfg(test)]
mod golden {
    use std::path::Path;

    /// Renders the fixture and compares it with the committed expectation.
    /// Set `UPDATE_GOLDEN=1` to rewrite the expectation after an intended change.
    #[test]
    fn minimal_fixture() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
        let resume =
            resume_model::load_file(dir.join("minimal.yaml")).unwrap_or_else(|e| panic!("{e}"));
        let actual = super::render(&resume).unwrap();
        let expected_path = dir.join("minimal.tex");
        if std::env::var_os("UPDATE_GOLDEN").is_some() {
            std::fs::write(&expected_path, &actual).unwrap();
        }
        let expected = std::fs::read_to_string(&expected_path)
            .expect("missing golden file; run with UPDATE_GOLDEN=1")
            .replace("\r\n", "\n");
        assert_eq!(
            actual, expected,
            "LaTeX output changed; rerun with UPDATE_GOLDEN=1 if intended"
        );
    }
}
